[http]
# 运行模式
debug = true
# 是否开启健康检查
health = true
# 启用的中间件
middlewares = ["logger", "cors"]
# http 绑定地址
bind-address = "0.0.0.0"
#  http 绑定端口
bind-port = 8090
# https 配置
cert-file = ""
private-key-file = ""
# 是否启用性能分析
enable-profiling = true
# 是否启用监控
enable-metrics = false

[grpc]
network = "tcp"
addr = ":3109"
timeout = 1
idle-timeout = 60
max-life-time = 7200
force-close-wait = 20
keep-alive-interval = 60
keep-alive-timeout = 20

[mysql]
# 连接地址
host = "127.0.0.1:3306"
# 用户名
username = "root"
# 密码
password = "root"
# 数据库名
database = "candle_light"
# 最大空闲连接数
max-idle-connections = 30
# 最大打开连接数
max-open-connections = 30
# 最大连接重用时长
max-connection-life-time = 30
# 是否开启sql日志打印
log-level = 4

[mongo]
uri = "mongodb://127.0.0.1:27017/test?authSource=admin"
poolLimit = 500

[redis]
# 连接地址
addr = ["127.0.0.1:6579"]
# 数据库编号
database = 15

[jwt]
Realm = "test zone"
key = "secret key"
timeout = 1
max-refresh = 2

[log]
# 日志输出路径
output-paths = ["stderr"]
# 日志级别
level = "INFO"
# 日志输出格式 json 和 console
format = "console"
# 是否禁用输出行号
disable-caller = false
# 是否禁用输出错误堆栈
disable-stacktrace = true
# 是否禁用颜色输出
enable-color = true
# 是否禁用开发模式
development = true
# 日志标签名
name = ""

[casbin]
model_path = "etc/rbac_model.conf"