// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	user2 "github.com/BooeZhang/gin-layout/internal/handler/v1/user"
	"github.com/BooeZhang/gin-layout/internal/repo/mysql"
	"github.com/BooeZhang/gin-layout/internal/router"
	"github.com/BooeZhang/gin-layout/internal/service/v1"
	"github.com/BooeZhang/gin-layout/internal/service/v1/user"
	"github.com/BooeZhang/gin-layout/server"
	"github.com/go-redis/redis/v8"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func initRouter(ds *gorm.DB, rs redis.UniversalClient) server.Router {
	userRepo := mysql.NewUserRepo(ds)
	serviceContext := v1.NewServiceContext(rs)
	serviceImpl := user.NewUserService(userRepo, serviceContext)
	handler := user2.NewUserHandler(serviceImpl)
	apiRouter := router.NewApiRouter(handler)
	return apiRouter
}

// wire.go:

var ApiRouterProviderSet = wire.NewSet(router.NewApiRouter, wire.Bind(new(server.Router), new(*router.ApiRouter)))
