// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/BooeZhang/gin-layout/core"
	user2 "github.com/BooeZhang/gin-layout/internal/handler/v1/user"
	"github.com/BooeZhang/gin-layout/internal/repo/mysql"
	"github.com/BooeZhang/gin-layout/internal/router"
	"github.com/BooeZhang/gin-layout/internal/service/v1"
	"github.com/BooeZhang/gin-layout/internal/service/v1/user"
	"github.com/BooeZhang/gin-layout/store"
	"github.com/google/wire"
)

// Injectors from wire.go:

func initRouter(st store.Storage) core.Router {
	serviceContext := v1.NewServiceContext(st)
	userRepo := mysql.NewUserRepo(st)
	serviceImpl := user.NewUserService(serviceContext, userRepo)
	handler := user2.NewUserHandler(serviceImpl)
	apiRouter := router.NewApiRouter(handler)
	return apiRouter
}

// wire.go:

var ApiRouterProviderSet = wire.NewSet(router.NewApiRouter, wire.Bind(new(core.Router), new(*router.ApiRouter)))
