info:
  contact: {}
paths:
  /user/:
    get:
      consumes:
      - application/json
      description: 获取用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取用户信息
      tags:
      - 用户
swagger: "2.0"
